export const URL = 'https://api.themoviedb.org/3/movie/popular';
export const API_KEY = '?api_key=0cff1e0b38424a5d25749f77eb90237b';
export const IMG_URL = 'https://image.tmdb.org/t/p/w500';
export const BACKDROP = 'https://image.tmdb.org/t/p/w500';
export const YOUTUBE = 'https://www.youtube.com/watch?v=';
export const TRAILER = 'https://api.themoviedb.org/3/movie/';
export const VIDEO = '/videos';
export const SEARCH = 'https://api.themoviedb.org/3/search/movie?query=';
export const SEARCH_KEY = '&api_key=0cff1e0b38424a5d25749f77eb90237b';
